# Generated by Django 5.2.3 on 2025-06-19 01:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(help_text='Name of the schedule', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the schedule')),
                ('owner', models.ForeignKey(help_text='Owner of the schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of the slot')),
                ('end_time', models.TimeField(help_text='End time of the slot')),
                ('ids', models.JSONField(default=list, help_text='List of IDs associated with this time slot')),
                ('schedule', models.ForeignKey(help_text='Schedule this time slot belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='schedules.schedule')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'db_table': 'time_slots',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('schedule', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
